module:
  hugoVersion:
    min: "0.61.0"
  mounts:
  - source: data
    target: data
  - source: assets
    target: assets/tnd-forms
  - source: partials
    target: layouts/partials/tnd-forms
  - source: shortcodes
    target: layouts/shortcodes
  - source: console
    target: layouts/partials/tnd-forms